### ISSUE TITLE
Application fails to start

### ISSUE THREAD

**Issue by EquusRaphanus** [OpenXbox/xbox-smartglass-nano-python#22]
I get the following error when I try to start:
```
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.AccessToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.RefreshToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.UserToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.XSTSToken'> from file
Traceback (most recent call last):
  File "/home/USER/.local/bin/xbox-nano-client", line 8, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/scripts/client.py", line 40, in main
    if len(discovered):
TypeError: object of type 'coroutine' has no len()
sys:1: RuntimeWarning: coroutine 'Console.discover' was never awaited
```

**Comment by tuxuser** [comment]
You are not running the latest version

From your virtual environment execute

```
pip install -U xbox-smartglass-nano
```

**Comment by EquusRaphanus** [comment]
Thanks for that! I did that, and now I'm getting another error:
```
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
Traceback (most recent call last):
  File "/home/USER/.local/bin/xbox-nano-client", line 8, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/scripts/client.py", line 59, in main
    loop.run_until_complete(async_main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/scripts/client.py", line 35, in async_main
    await console.connect("", "")
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/sg/console.py", line 381, in connect
    raise ConnectionError("Anonymous connection not allowed, please"
ConnectionError: Anonymous connection not allowed, please supply userhash and auth-token
```


I'm authenticated already for xbox-tui and that's working, but I'm not sure if this requires further authentication!

**Comment by tuxuser** [comment]
yeah, I did not re-implement authenticated connection... can you fallback to allow unauthenticated for now in xbox settings?

**Comment by EquusRaphanus** [comment]
Ahh ok, I see.


As it turns out, my xbox-tui authentication broke once I updated too, so disregard that from earlier. Disabling authenticated for now, hopefully that's re-implemented soon!

**Comment by EquusRaphanus** [comment]
I'm sorry for my confusion, but how would I allow unauthenticated connection in the xbox settings? I had assumed that was the "allow remote connection from any device", but I'm still getting the same error in both this and the following in xbox-tui:
```
Xbox SmartGlass main client started
Authenticating...
Traceback (most recent call last):
  File "/home/USER/.local/bin/xbox-tui", line 8, in <module>
    sys.exit(main_tui())
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/scripts/main_cli.py", line 623, in main_tui
    main(Commands.TUI)
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/scripts/main_cli.py", line 576, in main
    loop.run_until_complete(main_async(loop, command))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/scripts/main_cli.py", line 391, in main_async
    auth_manager = await do_authentication(args)
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/scripts/main_cli.py", line 265, in do_authentication
    auth_mgr.oauth = OAuth2TokenResponse.parse_raw(tokens)
  File "pydantic/main.py", line 538, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 515, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for OAuth2TokenResponse
token_type
  field required (type=value_error.missing)
expires_in
  field required (type=value_error.missing)
scope
  field required (type=value_error.missing)
access_token
  field required (type=value_error.missing)
refresh_token
  field required (type=value_error.missing)
user_id
  field required (type=value_error.missing)

```

**Comment by EquusRaphanus** [comment]
@tuxuser any advice? I haven't been able to get anything other than xbox-discover to work all day :(

**Comment by EquusRaphanus** [comment]
I removed my `~/.local/share/xbox/tokens.json'` file and tried re-running `xbox-authenticate`. That seemed to work for xbox-tui (which is no longer giving me an error), but `xbox-nano-client` is still giving the following error:

```
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
Traceback (most recent call last):
  File "/home/USER/.local/bin/xbox-nano-client", line 8, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/scripts/client.py", line 59, in main
    loop.run_until_complete(async_main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/scripts/client.py", line 35, in async_main
    await console.connect("", "")
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/sg/console.py", line 381, in connect
    raise ConnectionError("Anonymous connection not allowed, please"
ConnectionError: Anonymous connection not allowed, please supply userhash and auth-token

```

**Comment by EquusRaphanus** [comment]
I did a complete uninstall and reinstalled in a new venv. It looks like things are working a bit better now, but the application is still exiting with an error:

```
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Received DiscoverResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Sending ConnectRequest to 192.168.1.238
DEBUG:xbox.sg.protocol:Received ConnectResponse from 192.168.1.238
DEBUG:xbox.sg.protocol:Sending LocalJoin message on ServiceChannel Core to 192.168.1.238
DEBUG:xbox.sg.protocol:Received Ack message on ServiceChannel Ack from 192.168.1.238
DEBUG:xbox.sg.protocol:Received ConsoleStatus message on ServiceChannel Core from 192.168.1.238
DEBUG:xbox.sg.protocol:Sending StartChannelRequest message on ServiceChannel Core to 192.168.1.238
DEBUG:xbox.sg.protocol:Received Ack message on ServiceChannel Ack from 192.168.1.238
DEBUG:xbox.sg.protocol:Received StartChannelResponse message on ServiceChannel Core from 192.168.1.238
DEBUG:xbox.sg.protocol:Acquired ServiceChannel SystemInput -> Channel: 0x6
DEBUG:xbox.sg.protocol:Sending StartChannelRequest message on ServiceChannel Core to 192.168.1.238
DEBUG:xbox.sg.protocol:Received Ack message on ServiceChannel Ack from 192.168.1.238
DEBUG:xbox.sg.protocol:Sending StartChannelRequest message on ServiceChannel Core to 192.168.1.238
DEBUG:xbox.sg.protocol:Received Ack message on ServiceChannel Ack from 192.168.1.238
DEBUG:xbox.sg.protocol:Sending StartChannelRequest message on ServiceChannel Core to 192.168.1.238
DEBUG:xbox.sg.protocol:Received Ack message on ServiceChannel Ack from 192.168.1.238
DEBUG:xbox.sg.protocol:Sending StartChannelRequest message on ServiceChannel Core to 192.168.1.238
DEBUG:xbox.sg.protocol:Received Ack message on ServiceChannel Ack from 192.168.1.238
DEBUG:xbox.sg.protocol:Sending Ack message on ServiceChannel Core to 192.168.1.238
DEBUG:xbox.sg.protocol:Received StartChannelResponse message on ServiceChannel Core from 192.168.1.238
DEBUG:xbox.sg.protocol:Acquired ServiceChannel SystemInputTVRemote -> Channel: 0x7
DEBUG:xbox.sg.protocol:Received StartChannelResponse message on ServiceChannel Core from 192.168.1.238
DEBUG:xbox.sg.protocol:Acquired ServiceChannel SystemMedia -> Channel: 0x8
DEBUG:xbox.sg.protocol:Received StartChannelResponse message on ServiceChannel Core from 192.168.1.238
DEBUG:xbox.sg.protocol:Acquired ServiceChannel SystemText -> Channel: 0x9
DEBUG:xbox.sg.protocol:Received StartChannelResponse message on ServiceChannel Core from 192.168.1.238
DEBUG:xbox.sg.protocol:Acquired ServiceChannel SystemBroadcast -> Channel: 0xa
DEBUG:xbox.sg.protocol:Received Ack message on ServiceChannel Ack from 192.168.1.238
DEBUG:xbox.sg.protocol:Received Json message on ServiceChannel SystemBroadcast from 192.168.1.238
DEBUG:xbox.sg.protocol:Received Json message on ServiceChannel SystemBroadcast from 192.168.1.238
Traceback (most recent call last):
  File "/home/USER/.local/bin/xbox-nano-client", line 8, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/scripts/client.py", line 59, in main
    loop.run_until_complete(async_main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/scripts/client.py", line 41, in async_main
    await console.nano.start_stream()
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/nano/manager.py", line 89, in start_stream
    await self._send_json(msg.dict())
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/sg/manager.py", line 107, in _send_json
    return await self.console.json(data, channel=self._channel)
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/sg/console.py", line 357, in json
    return await self.protocol.send_message(data, channel=channel)
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/sg/protocol.py", line 133, in send_message
    if msg.header.pkt_type == PacketType.Message:
AttributeError: 'dict' object has no attribute 'header'
```

Both xbox-tui and this won't launch unless xbox-webapi-ex is installed (they coimplain about missing xbox.webapi.scripts.tui and xbox.webapi.authentication.manager respectively).

**Comment by EquusRaphanus** [comment]
Works in python 3.9
